import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useParams } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../auth/AuthProvider';
import { Empty, ErrorState, Loading, Status } from '../components/Feedback';
import { api, HttpError } from '../lib/api';
import { canUser } from '../lib/permissions';
import type { Asset, Employee, Page } from '../types';

const startSchema = z.object({ offboarding_date: z.string().min(1, 'Informe a data.'), reason: z.string().trim().min(3, 'Informe o motivo.').max(1000) });
const receiptSchema = z.object({ physical_condition: z.string().trim().min(2, 'Informe o estado fisico.').max(500), accessories: z.string().trim().max(1000).optional() });
const destinationSchema = z.object({ destination: z.enum(['BACKUP', 'EM_MANUTENCAO', 'DESATIVADO']), justification: z.string().trim().min(3, 'Informe a justificativa.').max(1000), technical_report: z.string().trim().max(5000).optional() }).superRefine((value, context) => { if (value.destination === 'DESATIVADO' && !value.technical_report) context.addIssue({ code: 'custom', path: ['technical_report'], message: 'Desativacao exige laudo tecnico.' }); });
const errorMessage = (error: unknown) => error instanceof HttpError || error instanceof Error ? error.message : 'Nao foi possivel concluir a operacao.';
function FieldError({ value }: { value?: string }) { return value ? <p className="field-error">{value}</p> : null; }

function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-label={title}><section className="card w-full max-w-lg"><div className="mb-4 flex items-center justify-between gap-4"><h2 className="text-lg font-bold">{title}</h2><button className="text-slate-600" onClick={close} aria-label="Fechar">Fechar</button></div>{children}</section></div>; }

function StartDialog({ employee, close }: { employee: Employee; close: () => void }) { const client = useQueryClient(); const form = useForm<z.infer<typeof startSchema>>({ resolver: zodResolver(startSchema), defaultValues: { offboarding_date: '', reason: '' } }); const submit = form.handleSubmit(async (values) => { try { await api(`/api/employees/${employee.id}/offboarding/start`, { method: 'POST', body: JSON.stringify(values) }); await client.invalidateQueries({ queryKey: ['offboarding-employees'] }); close(); } catch (error) { form.setError('root', { message: errorMessage(error) }); } }); return <Modal title="Iniciar desligamento" close={close}><p className="mb-4 text-sm text-slate-600">Funcionario: {employee.name}</p><form className="space-y-4" noValidate onSubmit={submit}><label className="label">Data de desligamento<input className="field" type="date" {...form.register('offboarding_date')} /></label><FieldError value={form.formState.errors.offboarding_date?.message} /><label className="label">Motivo<textarea className="field min-h-24" {...form.register('reason')} /></label><FieldError value={form.formState.errors.reason?.message} />{form.formState.errors.root && <p className="field-error" role="alert">{form.formState.errors.root.message}</p>}<button className="btn-primary" type="submit" disabled={form.formState.isSubmitting}>Confirmar inicio</button></form></Modal>; }

function RhPanel() { const [start, setStart] = useState<Employee>(); const active = useQuery({ queryKey: ['offboarding-employees', 'active'], queryFn: () => api<Page<Employee>>('/api/employees?page=1&pageSize=100&status=ativo') }); const leaving = useQuery({ queryKey: ['offboarding-employees', 'leaving'], queryFn: () => api<Page<Employee>>('/api/employees?page=1&pageSize=100&status=em_desligamento') }); if (active.isLoading || leaving.isLoading) return <Loading />; if (active.error || leaving.error) return <ErrorState error={active.error || leaving.error} />; return <section><h1 className="text-2xl font-bold">Desligamentos</h1><p className="mt-1 text-slate-600">Inicie e acompanhe o checklist de devolucao dos ativos.</p><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="card"><h2 className="font-bold">Funcionarios ativos</h2>{active.data!.items.length === 0 ? <p className="mt-3 text-sm text-slate-500">Nenhum funcionario ativo.</p> : <ul className="mt-3 space-y-3">{active.data!.items.map((employee) => <li className="flex items-center justify-between gap-3" key={employee.id}><span>{employee.name}</span><button className="btn-secondary" onClick={() => setStart(employee)}>Iniciar desligamento</button></li>)}</ul>}</section><section className="card"><h2 className="font-bold">Em desligamento</h2>{leaving.data!.items.length === 0 ? <p className="mt-3 text-sm text-slate-500">Nenhum desligamento em andamento.</p> : <ul className="mt-3 space-y-3">{leaving.data!.items.map((employee) => <li className="flex items-center justify-between gap-3" key={employee.id}><span>{employee.name}</span><Link className="btn-secondary" to={`/offboarding/${employee.id}`}>Abrir checklist</Link></li>)}</ul>}</section></div>{start && <StartDialog employee={start} close={() => setStart(undefined)} />}</section>; }

function ReceiveDialog({ asset, close }: { asset: Asset; close: () => void }) { const client = useQueryClient(); const form = useForm<z.infer<typeof receiptSchema>>({ resolver: zodResolver(receiptSchema), defaultValues: { physical_condition: '', accessories: '' } }); const submit = form.handleSubmit(async (values) => { try { await api(`/api/offboarding/assets/${asset.id}/receive`, { method: 'POST', body: JSON.stringify(values) }); await client.invalidateQueries({ queryKey: ['offboarding-assets'] }); close(); } catch (error) { form.setError('root', { message: errorMessage(error) }); } }); return <Modal title="Receber equipamento" close={close}><p className="mb-4 text-sm">{asset.hostname || asset.serial || `Ativo #${asset.id}`}</p><form className="space-y-4" noValidate onSubmit={submit}><label className="label">Estado fisico<textarea className="field min-h-20" {...form.register('physical_condition')} /></label><FieldError value={form.formState.errors.physical_condition?.message} /><label className="label">Acessorios<textarea className="field min-h-20" {...form.register('accessories')} /></label>{form.formState.errors.root && <p className="field-error" role="alert">{form.formState.errors.root.message}</p>}<button className="btn-primary" type="submit">Confirmar recebimento</button></form></Modal>; }
function DestinationDialog({ asset, close }: { asset: Asset; close: () => void }) { const client = useQueryClient(); const form = useForm<z.infer<typeof destinationSchema>>({ resolver: zodResolver(destinationSchema), defaultValues: { destination: 'BACKUP', justification: '', technical_report: '' } }); const destination = form.watch('destination'); const submit = form.handleSubmit(async (values) => { try { await api(`/api/offboarding/assets/${asset.id}/destination`, { method: 'POST', body: JSON.stringify(values) }); await client.invalidateQueries({ queryKey: ['offboarding-assets'] }); close(); } catch (error) { form.setError('root', { message: errorMessage(error) }); } }); return <Modal title="Definir destino" close={close}><p className="mb-4 text-sm">{asset.hostname || asset.serial || `Ativo #${asset.id}`}</p><form className="space-y-4" noValidate onSubmit={submit}><label className="label">Destino<select className="field" {...form.register('destination')}><option value="BACKUP">Backup</option><option value="EM_MANUTENCAO">Manutencao</option><option value="DESATIVADO">Desativacao</option></select></label><label className="label">Justificativa<textarea className="field min-h-20" {...form.register('justification')} /></label><FieldError value={form.formState.errors.justification?.message} />{destination === 'DESATIVADO' && <><label className="label">Laudo tecnico<textarea className="field min-h-24" {...form.register('technical_report')} /></label><FieldError value={form.formState.errors.technical_report?.message} /></>}{form.formState.errors.root && <p className="field-error" role="alert">{form.formState.errors.root.message}</p>}<button className="btn-primary" type="submit">Confirmar destino</button></form></Modal>; }

function TechnicianPanel() { const [receive, setReceive] = useState<Asset>(); const [destination, setDestination] = useState<Asset>(); const pending = useQuery({ queryKey: ['offboarding-assets', 'pending'], queryFn: () => api<Page<Asset>>('/api/assets?page=1&pageSize=100&status=PENDENTE_DEVOLUCAO') }); const evaluation = useQuery({ queryKey: ['offboarding-assets', 'evaluation'], queryFn: () => api<Page<Asset>>('/api/assets?page=1&pageSize=100&status=EM_AVALIACAO') }); if (pending.isLoading || evaluation.isLoading) return <Loading />; if (pending.error || evaluation.error) return <ErrorState error={pending.error || evaluation.error} />; const items = [...pending.data!.items, ...evaluation.data!.items]; return <section><h1 className="text-2xl font-bold">Fila tecnica de desligamento</h1><p className="mt-1 text-slate-600">Receba os equipamentos devolvidos e defina o destino.</p>{items.length === 0 ? <Empty>Nenhum ativo aguardando tratamento.</Empty> : <div className="card mt-6 overflow-x-auto"><table className="table"><thead><tr><th>Funcionario</th><th>Ativo</th><th>Status</th><th>Acao</th></tr></thead><tbody>{items.map((asset) => <tr key={asset.id}><td>{asset.employee_name || '-'}</td><td>{asset.hostname || asset.serial || `Ativo #${asset.id}`}</td><td><Status value={asset.status} /></td><td>{asset.status === 'PENDENTE_DEVOLUCAO' ? <button className="btn-secondary" onClick={() => setReceive(asset)}>Receber equipamento</button> : <button className="btn-secondary" onClick={() => setDestination(asset)}>Definir destino</button>}</td></tr>)}</tbody></table></div>}{receive && <ReceiveDialog asset={receive} close={() => setReceive(undefined)} />}{destination && <DestinationDialog asset={destination} close={() => setDestination(undefined)} />}</section>; }

type Checklist = { pending: number; received: number; evaluated: number; open_tickets: number; pending_deactivations: number; employee: { status: string }; assets: Asset[] };
export function OffboardingChecklistPage() { const { id } = useParams(); const client = useQueryClient(); const employee = useQuery({ queryKey: ['employee', id], queryFn: () => api<Employee>(`/api/employees/${id}`) }); const checklist = useQuery({ queryKey: ['offboarding-checklist', id], queryFn: () => api<Checklist>(`/api/employees/${id}/offboarding/checklist`) }); const conclude = useMutation({ mutationFn: () => api(`/api/employees/${id}/offboarding/conclude`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['offboarding-checklist', id] }); await client.invalidateQueries({ queryKey: ['offboarding-employees'] }); await client.invalidateQueries({ queryKey: ['employee', id] }); } }); if (employee.isLoading || checklist.isLoading) return <Loading />; if (employee.error || checklist.error) return <ErrorState error={employee.error || checklist.error} />; const value = checklist.data!; const canConclude = value.pending === 0 && value.received === 0 && value.open_tickets === 0 && value.pending_deactivations === 0; return <section><Link className="text-sm text-blue-700" to="/offboarding">Voltar para desligamentos</Link><h1 className="mt-4 text-2xl font-bold">Checklist: {employee.data!.name}</h1><div className="mt-6 grid gap-4 md:grid-cols-3"><section className="card"><p className="text-sm text-slate-500">Pendentes de recebimento</p><p className="mt-2 text-3xl font-bold">{value.pending}</p></section><section className="card"><p className="text-sm text-slate-500">Recebidos em avaliacao</p><p className="mt-2 text-3xl font-bold">{value.received}</p></section><section className="card"><p className="text-sm text-slate-500">Avaliados</p><p className="mt-2 text-3xl font-bold">{value.evaluated}</p></section></div><section className="card mt-5"><h2 className="font-bold">Ativos do desligamento</h2>{value.assets.length === 0 ? <p className="mt-3 text-sm text-slate-500">Nenhum ativo vinculado.</p> : <table className="table mt-3"><thead><tr><th>Ativo</th><th>Tipo</th><th>Status</th></tr></thead><tbody>{value.assets.map((asset) => <tr key={asset.id}><td>{asset.hostname || asset.serial || `Ativo #${asset.id}`}</td><td>{asset.equipment_type}</td><td><Status value={asset.status} /></td></tr>)}</tbody></table>}</section><section className="card mt-5"><h2 className="font-bold">Conclusao</h2><p className="mt-2 text-sm text-slate-600">Chamados abertos: {value.open_tickets}. Solicitacoes de desativacao pendentes: {value.pending_deactivations}.</p>{conclude.error && <p className="field-error mt-3" role="alert">{errorMessage(conclude.error)}</p>}<button className="btn-primary mt-4" disabled={!canConclude || conclude.isPending} onClick={() => conclude.mutate()}>Concluir desligamento</button>{!canConclude && <p className="mt-2 text-sm text-slate-500">A conclusao sera liberada quando nao houver pendencias.</p>}</section></section>; }

export function OffboardingPage() { const { user } = useAuth(); if (canUser(user, 'employee:offboard')) return <RhPanel />; if (canUser(user, 'asset:receive')) return <TechnicianPanel />; return <section className="card"><h1 className="text-2xl font-bold">Acesso negado</h1><p className="mt-2 text-slate-600">Sua conta nao pode operar desligamentos.</p></section>; }
